version: '3.8'

services:
  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rimhotel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
       REDIS_HOST: redis
    volumes:
      - ./:/var/www
    networks:
      - rimhotel_network
    depends_on:
      - postgres
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: rimhotel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rimhotel_network
    depends_on:
      - app

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: rimhotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rimhotel_db
      POSTGRES_USER: rimhotel_user
      POSTGRES_PASSWORD: rimhotel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rimhotel_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rimhotel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rimhotel_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: rimhotel_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rimhotel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - rimhotel_network
    depends_on:
      - postgres

networks:
  rimhotel_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
